# Public: Fire Emblem Fates characters and their preferences.
# 
# For fire-emblem-matcher

prefs = {
  # GENTLEMEN
  'laslow' => %w[femui azura peri camila luna felicia],
  'keaton' => %w[camilla effie hana],
  'xander' => %w[femui charlotte hinoka luna sakura],
  'leo' => %w[felicia hinoka sakura],
  'tsubaki' => %w[femui luna hinoka azura felicia hana oboro],
  'nishiki' => %w[femui azura sakura hana mozu],
  'jakob' => %w[femui azura sakura nyx],
  'niles' => %w[camilla mozu],
  'odin' => %w[elise nyx orochi],
  'silas' => %w[luna effie hinoka],
  'kaze' => %w[mozu beruka rinkah],
  'benny' => %w[peri charlotte camilla],
  'arthur' => %w[effie beruka camilla nyx],
  'ryoma' => %w[kagero orochi camilla],
  'takumi' => %w[azura felicia elise],
  'saizo' => %w[orochi beruka mozu],
  'hinata' => %w[hana hinoka setsuna],
  'azama' => %w[effie felicia setsuna beruka],
  'hayato' => %w[nyx sakura oboro],
  'gunter' => %w[femui],
  'izana' => %w[femui],
  'fuuga' => %w[femui],
  'yukimura' => %w[femui],
 
 # LADIES
  'azura' => %w[mamui laslow jakob nishiki takumi],
  'femui' => %w[laslow tsubaki xander jakob nishiki shigure leo], 
  'camilla' => %w[keaton niles jakob],
  'elise' => %w[odin takumi laslow],
  'felicia' => %w[leo takumi jakob azama],
  'luna' => %w[tsubaki silas laslow niles xander],
  'hinoka' => %w[leo xander hinata silas],
  'sakura' => %w[xander jakob leo hayato nishiki],
  'effie' => %w[keaton silas arthur],
  'beruka' => %w[saizo azama niles arthur],
  'kagero' => %w[ryoma saizo jakob],
  'peri' => %w[laslow benny xander],
  'hana' => %w[ryoma keaton hinata tsubaki],
  'oboro' => %w[takumi tsubaki hayato],
  'setsuna' => %w[hinata jakob azama],
  'rinkah' => %w[silas kaze nishiki ryoma],
  'charlotte' => %w[xander jakob keaton laslow],
  'mozu' => %w[nishiki niles kaze],
  'orochi' => %w[saizo ryoma silas jakob],
  'nyx' => %w[hayato niles odin],
  'flora' => %w[mamui],
  'scarlet' => %w[mamui],
  'mamui' => %w[flora],
}
